# Generated by Django 5.2.6 on 2025-10-30 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_type_user_is_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('clinic_address', models.CharField(blank=True, max_length=255)),
                ('clinic_city', models.CharField(blank=True, max_length=120)),
                ('clinic_phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='doctors/certificates/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
