# Generated by Django 5.2.6 on 2025-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
