# Generated by Django 5.2.6 on 2025-10-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_diseases', models.TextField(blank=True)),
                ('lab_tests', models.TextField(blank=True)),
                ('imaging_reports', models.TextField(blank=True)),
                ('chronic_diseases', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patientprofile')),
            ],
        ),
    ]
