# Generated by Django 5.2.6 on 2025-10-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment_uniq_doctor_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='uniq_doctor_datetime',
        ),
    ]
