# Generated by Django 5.2.6 on 2025-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_appointment_uniq_doctor_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(blank=True, help_text='الأدوية التي يتناولها المريض'),
        ),
    ]
